package com.example.stocka.Navigation

sealed class Destination(val routes:String){

    object SignUp:Destination("signup")
    object Login:Destination("login")
    object Home:Destination("home")
    object Stocks:Destination("stocks")
    object Customers:Destination("customers")
    object Invoices:Destination("invoices")
    object Settings:Destination("settings")
    object MakeSales:Destination("makeSales")
    object SalesInfo:Destination("salesInfo")
    object SalesInfoHome:Destination("salesInfoHome")
    object AddCustomer:Destination("addCustomer")
    object EditCustomer:Destination("editCustomer")
    object AddStock:Destination("addStock")
    object EditStock:Destination("editStock")
    object AddExpense:Destination("addExpense")
    object AddSale:Destination("addSale")
    object BottomSheet:Destination("sheet")
    object CustomerInfo:Destination("customerInfo")
    object CustomerHistory:Destination("customerHistory")
    object StockInfo:Destination("stockInfo")
    object StockHistory:Destination("stockHistory")
    object SearchStock:Destination("searchStock")
    object SearchCustomer:Destination("searchCustomer")
    object ExpenseInfo:Destination("expenseInfo")
    object EditSales:Destination("editSales")
    object AddCredit:Destination("addCredit")
    object MakeCredit:Destination("makeCredit")
    object CreditInfo:Destination("creditInfo")
    object CreditInfoHome:Destination("creditInfoHome")
    object PayCredit:Destination("payCredit")
    object ContactUs:Destination("contactUs")
    object AccountSecurity:Destination("accountSecurity")
    object BusinessDetails:Destination("businessDetails")
    object PersonalDetail:Destination("personalDetails")
    object EditPersonalDetail:Destination("editPersonalDetails")
    object EditBusinessDetail:Destination("editBusinessDetails")
    object SalesReceipt:Destination("salesReceipt")
    object CreditReceipt:Destination("creditReceipt")

}